controller_list:
  - name: fake_left_robot_controller
    type: $(arg fake_execution_type)
    joints:
      - leftshoulder_pan_joint
      - leftshoulder_lift_joint
      - leftelbow_joint
      - leftwrist_1_joint
      - leftwrist_2_joint
      - leftwrist_3_joint
  - name: fake_right_robot_controller
    type: $(arg fake_execution_type)
    joints:
      - rightshoulder_pan_joint
      - rightshoulder_lift_joint
      - rightelbow_joint
      - rightwrist_1_joint
      - rightwrist_2_joint
      - rightwrist_3_joint
  - name: fake_left_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - leftright_inner_knuckle_joint
  - name: fake_right_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - rightright_inner_knuckle_joint
initial:  # Define initial robot poses per group
  - group: left_robot
    pose: left_home
  - group: right_robot
    pose: right_home