controller_list:
  - name: fake_robot_controller
    type: $(arg fake_execution_type)
    joints:
      - leftshoulder_pan_joint
      - leftshoulder_lift_joint
      - leftelbow_joint
      - leftwrist_1_joint
      - leftwrist_2_joint
      - leftwrist_3_joint
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - leftright_inner_knuckle_joint
initial:  # Define initial robot poses per group
  - group: robot
    pose: home
  - group: gripper
    pose: open